version: "3.3"

services:
  app:
    build: .
    volumes:
    - ..:/app
    - bundle:/app/.bundle
    - tmp:/app/tmp
    - log:/app/log
    - bundle_install:/app/vendor/bundle
    ports:
    - 3000:3000
    extra_hosts:
      localhost: "${DOCKER_HOST_IP}"
    environment:
      USER: "${USER}"
    command: tail -f /dev/null

volumes:
  bundle:
  tmp:
  log:
  bundle_install:
